Device:
  OTAstatus: null
  key_device: 741c4116d85472ef
  key_from_server: O7GXs5chcAFBvVidAA4B
  type: '6004'
  version: 1.0.0
  wifi:
    SSID: Modelaiot
    password: 0853666060
    status: true
Unlock-Device:
- a7a52ebace42e4b0
- 776378273a99abf2
